# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(0, 0, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_result.setFont(font)
        self.label_result.setStyleSheet("background-color: rgb(145, 145, 145);\n"
"color: rgb(255, 255, 255);")
        self.label_result.setObjectName("label_result")
        self.btn_zero = QtWidgets.QPushButton(self.centralwidget)
        self.btn_zero.setGeometry(QtCore.QRect(0, 310, 150, 90))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.btn_zero.setFont(font)
        self.btn_zero.setStyleSheet("background-color: rgb(255, 190, 38);")
        self.btn_zero.setObjectName("btn_zero")
        self.btn_equal = QtWidgets.QPushButton(self.centralwidget)
        self.btn_equal.setGeometry(QtCore.QRect(150, 310, 150, 90))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.btn_equal.setFont(font)
        self.btn_equal.setStyleSheet("background-color: rgb(255, 105, 30);")
        self.btn_equal.setObjectName("btn_equal")
        self.btn_one = QtWidgets.QPushButton(self.centralwidget)
        self.btn_one.setGeometry(QtCore.QRect(0, 220, 80, 90))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.btn_one.setFont(font)
        self.btn_one.setStyleSheet("background-color: rgb(255, 190, 38);")
        self.btn_one.setObjectName("btn_one")
        self.btn_two = QtWidgets.QPushButton(self.centralwidget)
        self.btn_two.setGeometry(QtCore.QRect(80, 220, 80, 90))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.btn_two.setFont(font)
        self.btn_two.setStyleSheet("background-color: rgb(255, 190, 38);")
        self.btn_two.setObjectName("btn_two")
        self.btn_three = QtWidgets.QPushButton(self.centralwidget)
        self.btn_three.setGeometry(QtCore.QRect(160, 220, 80, 90))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.btn_three.setFont(font)
        self.btn_three.setStyleSheet("background-color: rgb(255, 190, 38);")
        self.btn_three.setObjectName("btn_three")
        self.btn_four = QtWidgets.QPushButton(self.centralwidget)
        self.btn_four.setGeometry(QtCore.QRect(0, 130, 80, 90))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.btn_four.setFont(font)
        self.btn_four.setStyleSheet("background-color: rgb(255, 190, 38);")
        self.btn_four.setObjectName("btn_four")
        self.btn_five = QtWidgets.QPushButton(self.centralwidget)
        self.btn_five.setGeometry(QtCore.QRect(80, 130, 80, 90))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.btn_five.setFont(font)
        self.btn_five.setStyleSheet("background-color: rgb(255, 190, 38);")
        self.btn_five.setObjectName("btn_five")
        self.btn_six = QtWidgets.QPushButton(self.centralwidget)
        self.btn_six.setGeometry(QtCore.QRect(160, 130, 80, 90))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.btn_six.setFont(font)
        self.btn_six.setStyleSheet("background-color: rgb(255, 190, 38);")
        self.btn_six.setObjectName("btn_six")
        self.btn_seven = QtWidgets.QPushButton(self.centralwidget)
        self.btn_seven.setGeometry(QtCore.QRect(0, 50, 80, 81))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.btn_seven.setFont(font)
        self.btn_seven.setStyleSheet("background-color: rgb(255, 190, 38);")
        self.btn_seven.setObjectName("btn_seven")
        self.btn_eight = QtWidgets.QPushButton(self.centralwidget)
        self.btn_eight.setGeometry(QtCore.QRect(80, 50, 80, 81))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.btn_eight.setFont(font)
        self.btn_eight.setStyleSheet("background-color: rgb(255, 190, 38);")
        self.btn_eight.setObjectName("btn_eight")
        self.btn_nine = QtWidgets.QPushButton(self.centralwidget)
        self.btn_nine.setGeometry(QtCore.QRect(160, 50, 80, 81))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.btn_nine.setFont(font)
        self.btn_nine.setStyleSheet("background-color: rgb(255, 190, 38);")
        self.btn_nine.setObjectName("btn_nine")
        self.btn_plus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_plus.setGeometry(QtCore.QRect(240, 50, 60, 78))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.btn_plus.setFont(font)
        self.btn_plus.setStyleSheet("background-color: rgb(255, 190, 38);")
        self.btn_plus.setObjectName("btn_plus")
        self.btn_minus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_minus.setGeometry(QtCore.QRect(240, 128, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.btn_minus.setFont(font)
        self.btn_minus.setStyleSheet("background-color: rgb(255, 190, 38);")
        self.btn_minus.setObjectName("btn_minus")
        self.btn_mult = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mult.setGeometry(QtCore.QRect(240, 188, 60, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.btn_mult.setFont(font)
        self.btn_mult.setStyleSheet("background-color: rgb(255, 190, 38);")
        self.btn_mult.setObjectName("btn_mult")
        self.btn_divide = QtWidgets.QPushButton(self.centralwidget)
        self.btn_divide.setGeometry(QtCore.QRect(240, 249, 60, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.btn_divide.setFont(font)
        self.btn_divide.setStyleSheet("background-color: rgb(255, 190, 38);")
        self.btn_divide.setObjectName("btn_divide")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

        self.is_equal = False

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор"))
        self.label_result.setText(_translate("MainWindow", "0"))
        self.btn_zero.setText(_translate("MainWindow", "0"))
        self.btn_equal.setText(_translate("MainWindow", "="))
        self.btn_one.setText(_translate("MainWindow", "1"))
        self.btn_two.setText(_translate("MainWindow", "2"))
        self.btn_three.setText(_translate("MainWindow", "3"))
        self.btn_four.setText(_translate("MainWindow", "4"))
        self.btn_five.setText(_translate("MainWindow", "5"))
        self.btn_six.setText(_translate("MainWindow", "6"))
        self.btn_seven.setText(_translate("MainWindow", "7"))
        self.btn_eight.setText(_translate("MainWindow", "8"))
        self.btn_nine.setText(_translate("MainWindow", "9"))
        self.btn_plus.setText(_translate("MainWindow", "+"))
        self.btn_minus.setText(_translate("MainWindow", "-"))
        self.btn_mult.setText(_translate("MainWindow", "*"))
        self.btn_divide.setText(_translate("MainWindow", "/"))

    def add_functions(self):
        self.btn_zero.clicked.connect(lambda: self.write_num(self.btn_zero.text()))
        self.btn_one.clicked.connect(lambda: self.write_num(self.btn_one.text()))
        self.btn_two.clicked.connect(lambda: self.write_num(self.btn_two.text()))
        self.btn_three.clicked.connect(lambda: self.write_num(self.btn_three.text()))
        self.btn_four.clicked.connect(lambda: self.write_num(self.btn_four.text()))
        self.btn_five.clicked.connect(lambda: self.write_num(self.btn_five.text()))
        self.btn_six.clicked.connect(lambda: self.write_num(self.btn_six.text()))
        self.btn_seven.clicked.connect(lambda: self.write_num(self.btn_seven.text()))
        self.btn_eight.clicked.connect(lambda: self.write_num(self.btn_eight.text()))
        self.btn_nine.clicked.connect(lambda: self.write_num(self.btn_nine.text()))
        self.btn_plus.clicked.connect(lambda: self.write_num(self.btn_plus.text()))
        self.btn_minus.clicked.connect(lambda: self.write_num(self.btn_minus.text()))
        self.btn_mult.clicked.connect(lambda: self.write_num(self.btn_mult.text()))
        self.btn_divide.clicked.connect(lambda: self.write_num(self.btn_divide.text()))

        self.btn_equal.clicked.connect(self.results)

    def write_num(self, num):
        if self.label_result.text() == '0' or self.is_equal:
            self.label_result.setText(num)
            self.is_equal = False
        else:
            self.label_result.setText(self.label_result.text() + num)

    def results(self):
        if not self.is_equal:
            if '/0' in self.label_result.text():
                error_divide = QMessageBox()
                error_divide.setWindowTitle('Ошибка')
                error_divide.setText('Нельзя делить на ноль!')
                error_divide.setIcon(QMessageBox.Warning)
                error_divide.setStandardButtons(QMessageBox.Ok|QMessageBox.Cancel|QMessageBox.Reset)
                error_divide.buttonClicked.connect(self.popup_action)

                error_divide.exec_()

            elif self.label_result.text().count('*') > 2:
                some_error = QMessageBox
                some_error.setWindowTitle('Ошибка')
                some_error.setText('Неизвесная ошибка')
                some_error.setIcon(QMessageBox.Warning)
                some_error.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel | QMessageBox.Reset)
                some_error.buttonClicked.connect(self.popup_action)

                some_error.exec_()

            else:
                res = eval(self.label_result.text())  
                self.label_result.setText('Результат: ' + str(res))
                self.is_equal = True

        else:
            error = QMessageBox()
            error.setWindowTitle('Ошибка')
            error.setText('Сейчас это действие выполнить нельзя')
            error.setIcon(QMessageBox.Warning)
            error.setStandardButtons(QMessageBox.Ok|QMessageBox.Cancel|QMessageBox.Reset)
            error.buttonClicked.connect(self.popup_action)

            error.exec_()

    def popup_action(self, btn):
        if btn.text() == 'Ok':
            print('Print Ok')
        elif btn.text() == 'Reset':
            self.label_result.setText('')
            self.is_equal = False


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
